### ISSUE TITLE
[PE-D][Tester C] Clearing address book also removes assigned person from the project

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T08-2/tp#158] opened 2022-10-29 03:12 UTC
To reproduce:
1. Add tasks and assign a contact to them
2. `clear`
3. The assignee should have disappeared from the task as well

It is unexpected for `clear` to have a sideeffect on tasks since the function is only implemented for the adddress book.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: SeekSaveServe/ped#7

**Comment by KIANSEONG** [comment] 2022-10-31 08:55
<img width="1440" alt="Screenshot 2022-10-31 at 4 54 02 PM" src="https://user-images.githubusercontent.com/53166471/198969579-7e05ab87-94fd-4a87-8919-cfda0ac78c58.png">
<img width="1440" alt="Screenshot 2022-10-31 at 4 54 15 PM" src="https://user-images.githubusercontent.com/53166471/198969571-2adb81ae-8084-4f4a-9486-dbc9a0abbc88.png">
<img width="1440" alt="Screenshot 2022-10-31 at 4 54 36 PM" src="https://user-images.githubusercontent.com/53166471/198969559-7b3857ed-3481-4456-9abc-4c90ca471aad.png">

Unable to reproduce.

**Comment by kianseong** [comment] 2022-11-06 06:19
Closed as already updated in UG.

**Closed as completed by kianseong** 2022-11-06 06:19 UTC
Labels: type.DocumentationBug
